<CameraClick>:
    orientation: 'vertical'
    Camera:
        id: camera  #相机
        resolution: (640, 480)
        play: False
    ToggleButton:
        text: 'Play'  #打开相机
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'   #截图
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()